### ISSUE TITLE
Rename `Chart` to `View`?

### ISSUE THREAD

**Issue by sehilyi** [manzt/ipygosling#10]
Since both `Track` and `View` are important concepts in Gosling, I think we can support explicit functions for both in the python package as well. In this regard, I was wondering whether it makes sense to rename `Chart` to `View` since `Chart()` looks to construct Gosling's views.

```python
// from
gos.Chart(
    title='Overview and Detail Views',
    arrangement='horizontal',
    views=[overview, detail_view]
)

// to
gos.View(
    title='Overview and Detail Views',
    arrangement='horizontal',
    views=[overview, detail_view] // two children views that are nested in this parent view
)
```

So, at the root level, users define a `View`, and it can contain either multiple `View`s or `Track`s.

**Comment by manzt** [comment]
The challenge here is that `gosling.Chart` inherits from `gosling.schema.Root` (and additional "mixin" classes that add short-hands for setting properties / displaying the Root in a notebook). The `Root` type is different from both `SingleView` and `MultipleViews` (adds `title`, `subtitle`, `description`), so I think it's important to establish a "root" type unambiguously

**Comment by sehilyi** [comment]
I didn't realize that the `View` is not directly included in the `GoslingSpec`. I think I can include `View` somewhere, e.g., at the root level of `GoslingSpec`, so that it can be included in the python package as well. The two terms "tracks" and "views" are taken from [the taxonomy of genomics visualization](https://onlinelibrary.wiley.com/doi/10.1111/cgf.13727), so we probably would need to keep that as is in the package.

My one concern was that the name of `Chart()` could be confusing to users given that we already have two terms, i.e., "track" and "view", that denote visualizations or sets of visualizations. If we want to keep the "root" type unambiguously, I think we could use another name (e.g., "Root" or something else).

My initial thought was to somehow combine the `View` and "root" types and expose only `View` to users (e.g., when a user defines "title" and/or "subtitle" at the root level, then the package considers this as the "root" type) since the only difference between the two types is the few additional properties in the "root" type. In general, I think it might be easier to use the package if very similar properties can be merged so that users do not necessarily have to memorize a larger number of properties and select a proper one among them. But, there might be downsides of this that I am missing.

**Comment by manzt** [comment]
>  If we want to keep the "root" type unambiguously, I think we could use another name (e.g., "Root" or something else).

I see your point, and mostly agree. Perhaps `Root` is likely a good option. I liked `Chart` because then there was a nice link between `gos.Chart` and the `Track(...).chart()` methods. To me, I thought it was more intuitive than `gos.Track().root()` for example.

**Comment by sehilyi** [comment]
Since `overlay`ing tracks in Gosling is very similar with `layer`ing in Vega-Lite, I wondered how they support `layer`ing in the Altair.

Overlaying tracks in Gosling:
```js
{
   alignment: 'overlay',
   data: {...}, // common properties of Track A-B are defined here
   tracks: [
      { /* Track A */ },  // partial spec
      { /* Track B */ }   // partial spec
   ]
}
```

Overlaying charts in Vega-Lite [(link)](https://vega.github.io/vega-lite/examples/trellis_bar.html):
```js
{
   data: {...}, // common properties of Chart A-B are defined here
   layer: [
      { /* Chart A */ },  // partial spec
      { /* Chart B */ }   // partial spec
   ]
}
```

Overlaying charts in Altair:
```py

chartA = alt.Chart(df).encode(...) # Complete spec that requires data, mark, etc
chartB = alt.Chart(df).encode(...) # Complete spec that requires data, mark, etc

alt.layer(chartA, chartB) # or `chartA + chartB`
```

It looks like Altair does not support the partial specification at all, which is currently supported in Vega-Lite. One of the reasons the partial specification is supported in Gosling (and in Vega-Lite I think) is to prevent code repetition, and my guess is that they do not support partial specification in Altair since this issue (repetition) can be easily handled by the programmatical approach. So, if we want to follow a similar approach, we can let users use `Track()`, which already works in our package:

```python
overlay_base = gos.Track(data=mv)

bar_base.properties(
    ..., 
    alignment='overlay',
    tracks=[
        overlay_base.mark_bar().encode(...),
        overlay_base.mark_brush().encode(...),
        overlay_base.mark_brush().encode(...)
    ]
)
```

**Comment by sehilyi** [comment]
Another thing I realized is that Altair does not seem to expose types at all (or may a few) that are beyond a chart level. For example, instead of `alt.HConcatSpec()`, Altair let users use `|` or `alt.hconcat()` to generate `{ hconcat: [{...}, {...}] }` specs. So, I wonder if we want to (or you are planning to) deprecate the use of `tracks=[...]` and let users use such operations:

```python
a = overlay_base.mark_bar().encode(...)
b = overlay_base.mark_brush().encode(...)
c = overlay_base.mark_brush().encode(...)

d = (a + b + c) # SingleTrack
```
But, I am not sure how and if we can use these for both the track and view composition. For example, would something like the following work?

```python
v1 = gos.overlay(a, b) # { alignemet: "overlay", tracks: [ /* a */, /* b */ ] }
v2 = gos.stack(a, b) # { alignemet: "stack", tracks: [ /* a */, /* b */ ] }

gos.horizontal(v1, v2) # { arrangement: "horizontal", views: [/* v1 */, /* v2 */] }
gos.vertical(v1, v2) # { arrangement: "vertical", views: [/* v1 */, /* v2 */] }
gos.parallel(v1, v2) # { arrangement: "parallel", views: [/* v1 */, /* v2 */] }
gos.serial(v1, v2) # { arrangement: "serial", views: [/* v1 */, /* v2 */] }

# specify additional multi-view-level properties
gos.serial(a, b, spacing=30) # { arrangement: "serial", views: [/* v1 */, /* v2 */] }
...
```

Probably these are something that you already thought of, but I wanted to hear what are your thoughts on this. And, sorry, this became too long than I expected 😅

**Comment by manzt** [comment]
Thanks for all the thoughtful ideas. This is sort of what I had in mind already and have started implementing to some extent.

> One of the reasons the partial specification is supported in Gosling (and in Vega-Lite I think) is to prevent code repetition, and my guess is that they do not necessarily support the partial specification since this issue (repetition) can be easily handled by the programmatical approach.

Completely agree. I'm thinking that for now, we don't expose the `PartialTrack` and instead just work with complete `Track`'s. This will make the JSON larger at the end, but that is OK IMO. If it becomes an issue, we can always write a script to strip out duplicated (unecessary) fields :)

Additionally, thank you for all the examples and explanation. It helps a lot for me to understand gosling's data-model much better. You have actually identified a bug with the current implementation. The class `Track` should _only_ be able to hold fields for a gosling `Track`, but the `properties` API is sneaky because it allows a hook to add additional fields (which) actually turn the Track into a View! For example,

```python
track4 = Track(multivec).encode(
    x=gos.Channel("position:G", axis="top"),
    y="peak:Q",
    row="sample:N",
    color=gos.Channel("sample:N", legend=True),
    tooltip=tooltip,
).properties(
    alignment="overlay",
    tracks=[
        gos.PartialTrack().mark_line(),
        gos.PartialTrack().mark_point().encode(
            size=gos.Channel("peak:Q", range=[0, 2]),
        )
    ],
)
```

"Works" because the constructor for `Track` is called with proper arguments and passes validation. The assignment in the `.properties` method adds these fields to the `Track` instance, but effectively changes the type from a track to a `SingleView`. The way that the validation ends up working, this is still valid in the end. But for example if you call `Track` like below,

```python
gos.Track(
    multivec,
    alignment="overlay",
    tracks=[
        gos.PartialTrack().mark_line(),
        gos.PartialTrack().mark_point().encode(
            size=gos.Channel("peak:Q", range=[0, 2]),
        )
    ],
)

# gosling.schemapi.SchemaValidationError: Invalid specification
#
#        gosling.api.Track->0, validating 'additionalProperties'
#
#        Additional properties are not allowed ('alignment', 'tracks' were unexpected)
```

It results in an error. The idea with `properties` is to have a nice shorthand modify the class instance. So technically,

```python
gos.Track(data, ...)

# and 

gos.Track(data).properties(...) 
```

should be equivalent. The fact that the example still compiled with the `Track(data).properties(alignemnt=..., tracks=...)` confused me about what the types in gosling actually are. But now I can see clearly what's going on.

Thanks for all your help. I'm goign to work on the API today and will ping you when I have something cleaned up :)
