### ISSUE TITLE
Unify the use of `properties` in `Track` and `Chart`?

### ISSUE THREAD

**Issue by sehilyi** [manzt/ipygosling#11]
It looks like non-encoding-related properties (e.g., `alignment`, `arrangement`) are defined either inside `properties(...)` or directly in `Track(...)/Chart(...)`:

```python
gos.Track(...).encoding(...).properties(
   alignment="stack"
)

// vs

gos.Chart(
   arrangement="horizontal"
)

gos.Chart().properties(arrangement="horizontal") // error, no `Chart().properties()`
```

Perhaps, we can think about how to unify Track and Chart, and which options we want to support in each of `properties(...)`, `Track(...)`, and `Chart(...)`.

**Comment by manzt** [comment]
I think this is a good idea! The "top-level" api is still a bit abstract in the moment in terms of design, but this makes sense to me. There isn't a total 1:1 correspondence of the vega-lite model and gosling, so we will need to experiment with what APIs work.
