### ISSUE TITLE
Revise error messages in the context of Gosling?

### ISSUE THREAD

**Issue by sehilyi** [manzt/ipygosling#21]
Not that important for now, but we can edit error or warning messages to make it more understandable in the context of Gosling, if possible.

For example, "chart specification" in the following screenshot can be changed to "view specification," or more generally "gosling specification."

<img width="779" alt="Screen Shot 2021-08-20 at 12 03 14 PM" src="https://user-images.githubusercontent.com/9922882/130261740-71daa61e-3491-4de5-97bd-78fd188e0313.png">

**Comment by manzt** [comment]
Agreed! Here is the bit of code if you want to submit a PR: https://github.com/manzt/ipygosling/blob/d24e89bb7a0d13d36d75f12876cf89e89c8e8ff1/src/index.ts#L37-L44

**Comment by sehilyi** [comment]
Thank you for sharing it!
